"""Append remaining methods to env.py"""
import os

PATH = os.path.join(os.path.dirname(__file__), 'env.py')

# Full NLE monster/item symbol tables
MONSTER_NAMES = {
    'a': 'ant/other insect', 'b': 'bat', 'c': 'centipede', 'd': 'dog/canine',
    'e': 'eye/sphere', 'f': 'cat/feline', 'g': 'gremlin', 'h': 'humanoid',
    'i': 'imp/minor demon', 'j': 'jelly', 'k': 'kobold', 'l': 'leprechaun',
    'm': 'mimic', 'n': 'nymph', 'o': 'orc', 'p': 'piercer', 'q': 'quadruped',
    'r': 'rodent', 's': 'spider/arachnid', 't': 'trapper/lurker', 'u': 'unicorn',
    'v': 'vortex', 'w': 'worm', 'x': 'xan/other insect', 'y': 'yellow light',
    'z': 'zombie', 'A': 'angel', 'B': 'bat (large)', 'C': 'centaur',
    'D': 'dragon', 'E': 'elemental', 'F': 'freezing sphere', 'G': 'gnome',
    'H': 'giant humanoid', 'I': 'invisible stalker', 'J': 'jellyfish',
    'K': 'ki-rin', 'L': 'lich', 'M': 'mummy', 'N': 'naga', 'O': 'ogre',
    'P': 'pudding/ooze', 'Q': 'quantum mechanic', 'R': 'rust monster',
    'S': 'snake', 'T': 'troll', 'U': 'umber hulk', 'V': 'vampire',
    'W': 'wraith', 'X': 'xorn', 'Y': 'yeti', 'Z': 'zombie (large)',
    '&': 'demon', ';': 'sea monster', ':': 'lizard',
}

ITEM_NAMES = {
    '!': 'potion (use drink)',
    '?': 'scroll (use read)',
    '/': 'wand (use zap)',
    '=': 'ring (use put on)',
    '"': 'amulet (use put on)',
    '[': 'armor (use wear)',
    ')': 'weapon (use wield)',
    '(': 'tool/misc item',
    '*': 'gem/rock',
    ',': 'food item (use eat)',
    '+': 'spellbook (use read)',
    '$': 'gold (use pickup)',
    '%': 'food (use pickup then eat)',
    '`': 'boulder/statue',
    '{': 'fountain',
    '^': 'trap - avoid',
    '_': 'altar',
}

APPEND = (
    "\n"
    "    # Full symbol translation table\n"
    "    _MONSTER_NAMES = " + repr(MONSTER_NAMES) + "\n"
    "    _ITEM_NAMES = " + repr(ITEM_NAMES) + "\n"
    "\n"
    "    def _symbol_legend(self, obs):\n"
    "        chars = obs['tty_chars']\n"
    "        b = obs['blstats']\n"
    "        px, py = int(b[0]), int(b[1])\n"
    "        seen = {}\n"
    "        for r in range(1, 22):\n"
    "            for c in range(MAP_COLS):\n"
    "                ch = chr(chars[r][c])\n"
    "                if ch in MONSTER_SYMS and ch not in seen:\n"
    "                    seen[ch] = '{} = {} (MONSTER - fight by moving into it or flee)'.format(ch, self._MONSTER_NAMES.get(ch, 'monster'))\n"
    "                elif ch in ITEM_SYMS and ch not in seen:\n"
    "                    seen[ch] = '{} = {} (use pickup)'.format(ch, self._ITEM_NAMES.get(ch, 'item'))\n"
    "                elif ch in _TILE_LABEL and ch not in ('.', '#', ' ', '@') and ch not in seen:\n"
    "                    seen[ch] = '{} = {}'.format(ch, _TILE_LABEL[ch])\n"
    "        if not seen:\n"
    "            return ''\n"
    "        return 'Symbol legend:\\n  ' + '\\n  '.join(seen.values())\n"
    "\n"
    "    # Map cache\n"
    "\n"
    "    def _update_map_cache(self, obs):\n"
    "        chars = obs['tty_chars']\n"
    "        b = obs['blstats']\n"
    "        px, py = int(b[0]), int(b[1])\n"
    "        for r in range(MAP_ROWS):\n"
    "            for c in range(MAP_COLS):\n"
    "                ch = chr(chars[r + 1][c])\n"
    "                if ch in _TERRAIN:\n"
    "                    self._map_cache[r][c] = ch\n"
    "        cr = py - 1\n"
    "        if 0 <= cr < MAP_ROWS and 0 <= px < MAP_COLS:\n"
    "            if self._map_cache[cr][px] == ' ':\n"
    "                self._map_cache[cr][px] = '.'\n"
    "\n"
    "    def _render_map_cache(self, obs):\n"
    "        chars = obs['tty_chars']\n"
    "        rows = []\n"
    "        for r in range(MAP_ROWS):\n"
    "            row = list(self._map_cache[r])\n"
    "            for c in range(MAP_COLS):\n"
    "                ch = chr(chars[r + 1][c])\n"
    "                if ch in _TRANSIENT:\n"
    "                    row[c] = ch\n"
    "            rows.append('{:2d} {}'.format(r + 1, ''.join(row)))\n"
    "        ruler_tens = '   ' + ''.join(str(c // 10) if c % 10 == 0 else ' ' for c in range(MAP_COLS))\n"
    "        ruler_ones = '   ' + ''.join(str(c % 10) for c in range(MAP_COLS))\n"
    "        return ruler_tens + '\\n' + ruler_ones + '\\n' + '\\n'.join(rows)\n"
    "\n"
    "    # BFS pathfinding\n"
    "\n"
    "    def _bfs(self, sx, sy, targets):\n"
    "        WALKABLE = set('.#<>+$%`_' + chr(92) + '{') | MONSTER_SYMS | ITEM_SYMS\n"
    "        visited = {(sx, sy - 1)}\n"
    "        q = deque([(sx, sy - 1, [])])\n"
    "        while q:\n"
    "            cx, cr, path = q.popleft()\n"
    "            if (cx, cr + 1) in targets:\n"
    "                return path, (cx, cr + 1)\n"
    "            for name, dx, dy in DIRS8:\n"
    "                nx, nr = cx + dx, cr + dy\n"
    "                if (nx, nr) in visited:\n"
    "                    continue\n"
    "                if not (0 <= nr < MAP_ROWS and 0 <= nx < MAP_COLS):\n"
    "                    continue\n"
    "                ch = self._map_cache[nr][nx]\n"
    "                if ch not in WALKABLE:\n"
    "                    continue\n"
    "                visited.add((nx, nr))\n"
    "                q.append((nx, nr, path + [name]))\n"
    "        return None, None\n"
    "\n"
    "    # Room analysis\n"
    "\n"
    "    def _room_exits(self, px, py):\n"
    "        FLOOR = set('.<>_`{' + chr(92))\n"
    "        cr0 = py - 1\n"
    "        if not (0 <= cr0 < MAP_ROWS and 0 <= px < MAP_COLS):\n"
    "            return None\n"
    "        if self._map_cache[cr0][px] not in FLOOR:\n"
    "            return None\n"
    "        room = set()\n"
    "        stack = [(px, cr0)]\n"
    "        while stack:\n"
    "            cx, cr = stack.pop()\n"
    "            if (cx, cr) in room or not (0 <= cr < MAP_ROWS and 0 <= cx < MAP_COLS):\n"
    "                continue\n"
    "            if self._map_cache[cr][cx] not in FLOOR:\n"
    "                continue\n"
    "            room.add((cx, cr))\n"
    "            for dx, dy in DIRS4:\n"
    "                stack.append((cx + dx, cr + dy))\n"
    "        corridors, doors, gaps = set(), set(), set()\n"
    "        for cx, cr in room:\n"
    "            for dx, dy in DIRS4:\n"
    "                nx, nr = cx + dx, cr + dy\n"
    "                if not (0 <= nr < MAP_ROWS and 0 <= nx < MAP_COLS):\n"
    "                    continue\n"
    "                ch = self._map_cache[nr][nx]\n"
    "                coord = (nx, nr + 1)\n"
    "                if ch == '#':\n"
    "                    corridors.add(coord)\n"
    "                elif ch == '+':\n"
    "                    doors.add(coord)\n"
    "                elif ch in '|-':\n"
    "                    ex, er = nx + dx, nr + dy\n"
    "                    if 0 <= er < MAP_ROWS and 0 <= ex < MAP_COLS and self._map_cache[er][ex] == ' ':\n"
    "                        gaps.add(coord)\n"
    "        return {'corridors': sorted(corridors), 'doors': sorted(doors), 'unexplored_gaps': sorted(gaps)}\n"
    "\n"
    "    def _passable_neighbors(self, px, py):\n"
    "        PASSABLE = set('.#<>+$%`_' + chr(92) + '{') | MONSTER_SYMS | ITEM_SYMS\n"
    "        passable, unexplored = [], []\n"
    "        for name, dx, dy in DIRS8:\n"
    "            nx, ny = px + dx, py + dy\n"
    "            cr = ny - 1\n"
    "            if 0 <= cr < MAP_ROWS and 0 <= nx < MAP_COLS:\n"
    "                ch = self._map_cache[cr][nx]\n"
    "                if ch in PASSABLE:\n"
    "                    passable.append((name, nx, ny, ch))\n"
    "                elif ch == ' ':\n"
    "                    unexplored.append((name, nx, ny))\n"
    "        return passable, unexplored\n"
    "\n"
    "    # Status helpers\n"
    "\n"
    "    def _status_warnings(self, obs):\n"
    "        b = obs['blstats']\n"
    "        hp, hpmax = int(b[10]), int(b[11])\n"
    "        hunger = int(b[21])\n"
    "        encumbrance = int(b[22]) if len(b) > 22 else 0\n"
    "        warnings = []\n"
    "        if hpmax > 0:\n"
    "            pct = hp / hpmax\n"
    "            if pct < 0.25:\n"
    "                warnings.append('WARNING: CRITICAL HP ({}/{}) - flee or heal immediately'.format(hp, hpmax))\n"
    "            elif pct < 0.5:\n"
    "                warnings.append('WARNING: Low HP ({}/{}) - consider retreating'.format(hp, hpmax))\n"
    "        if hunger >= 2:\n"
    "            warnings.append('WARNING: {} - eat food now'.format(_HUNGER_LABEL.get(hunger, 'hungry')))\n"
    "        if encumbrance >= 2:\n"
    "            warnings.append('WARNING: {} - drop items'.format(_ENCUMBRANCE_LABEL.get(encumbrance, 'encumbered')))\n"
    "        if self._prev_hp is not None and hp < self._prev_hp:\n"
    "            warnings.append('WARNING: Took {} damage this turn'.format(self._prev_hp - hp))\n"
    "        self._prev_hp = hp\n"
    "        return warnings\n"
    "\n"
    "    # Priority advisor\n"
    "\n"
    "    def _priority(self, obs, stairs_down, monsters, items):\n"
    "        b = obs['blstats']\n"
    "        hp, hpmax = int(b[10]), int(b[11])\n"
    "        hunger = int(b[21])\n"
    "        px, py = int(b[0]), int(b[1])\n"
    "        if hpmax > 0 and hp / hpmax < 0.25:\n"
    "            return 'PRIORITY: HP critical - flee from monsters, find healing'\n"
    "        if hunger >= 3:\n"
    "            food = [i for i in items if '%' in i]\n"
    "            if food:\n"
    "                return 'PRIORITY: Starving - pickup food at {}'.format(food[0])\n"
    "            return 'PRIORITY: Starving - check inventory for food (use eat action)'\n"
    "        if stairs_down:\n"
    "            path, dest = self._bfs(px, py, set(stairs_down))\n"
    "            if path:\n"
    "                return 'PRIORITY: Go to stairs down at {} - next step: {} ({} steps)'.format(dest, path[0], len(path))\n"
    "            return 'PRIORITY: Stairs down known at {} but no path - explore corridors'.format(stairs_down[0])\n"
    "        exits = self._room_exits(px, py)\n"
    "        if exits:\n"
    "            if exits['unexplored_gaps']:\n"
    "                g = exits['unexplored_gaps'][0]\n"
    "                path, _ = self._bfs(px, py, {g})\n"
    "                step = path[0] if path else '?'\n"
    "                return 'PRIORITY: Explore unexplored gap at {} - next step: {}'.format(g, step)\n"
    "            if exits['corridors']:\n"
    "                path, dest = self._bfs(px, py, set(exits['corridors']))\n"
    "                if path:\n"
    "                    return 'PRIORITY: Follow corridor at {} - next step: {}'.format(dest, path[0])\n"
    "            if exits['doors']:\n"
    "                path, dest = self._bfs(px, py, set(exits['doors']))\n"
    "                if path:\n"
    "                    return 'PRIORITY: Open door at {} - next step: {}'.format(dest, path[0])\n"
    "        return 'PRIORITY: Stairs not found - search every room corner, use search action near walls'\n"
    "\n"
    "    # Features\n"
    "\n"
    "    def _map_features(self, obs):\n"
    "        chars = obs['tty_chars']\n"
    "        b = obs['blstats']\n"
    "        px, py = int(b[0]), int(b[1])\n"
    "        stairs_down, stairs_up, doors, monsters, items = [], [], [], [], []\n"
    "        for r in range(MAP_ROWS):\n"
    "            for c in range(MAP_COLS):\n"
    "                ch = self._map_cache[r][c]\n"
    "                coord = (c, r + 1)\n"
    "                if ch == '>':\n"
    "                    stairs_down.append(coord)\n"
    "                elif ch == '<':\n"
    "                    stairs_up.append(coord)\n"
    "                elif ch == '+':\n"
    "                    doors.append(coord)\n"
    "        for r in range(1, 22):\n"
    "            for c in range(MAP_COLS):\n"
    "                ch = chr(chars[r][c])\n"
    "                coord = (c, r)\n"
    "                if ch in MONSTER_SYMS:\n"
    "                    monsters.append('{}@{}'.format(ch, coord))\n"
    "                elif ch in ITEM_SYMS:\n"
    "                    items.append('{}@{}'.format(ch, coord))\n"
    "        lines = []\n"
    "        for w in self._status_warnings(obs):\n"
    "            lines.append(w)\n"
    "        lines.append(self._priority(obs, stairs_down, monsters, items))\n"
    "        lines.append('')\n"
    "        cr = py - 1\n"
    "        terrain = ''\n"
    "        if 0 <= cr < MAP_ROWS and 0 <= px < MAP_COLS:\n"
    "            ch = self._map_cache[cr][px]\n"
    "            terrain = 'corridor' if ch == '#' else 'room floor' if ch == '.' else ch\n"
    "        lines.append('Player: ({},{}) on {}'.format(px, py, terrain))\n"
    "        lines.append('Stairs down(>): {}'.format(stairs_down if stairs_down else 'not found yet - keep exploring'))\n"
    "        if stairs_up:\n"
    "            lines.append('Stairs up(<): {}'.format(stairs_up))\n"
    "        if monsters:\n"
    "            lines.append('Monsters visible: {}'.format(' '.join(monsters)))\n"
    "        if items:\n"
    "            lines.append('Items on floor: {}'.format(' '.join(items)))\n"
    "        passable, unexplored = self._passable_neighbors(px, py)\n"
    "        if passable:\n"
    "            nb_strs = []\n"
    "            for name, nx, ny, ch in passable:\n"
    "                if ch in _TILE_LABEL:\n"
    "                    label = _TILE_LABEL[ch]\n"
    "                elif ch in MONSTER_SYMS:\n"
    "                    label = 'MONSTER({}) {}'.format(ch, NLEEnv._MONSTER_NAMES.get(ch, ''))\n"
    "                elif ch in ITEM_SYMS:\n"
    "                    label = 'item({}) {}'.format(ch, NLEEnv._ITEM_NAMES.get(ch, ''))\n"
    "                else:\n"
    "                    label = ch\n"
    "                nb_strs.append('{}->({},{})[{}]'.format(name, nx, ny, label))\n"
    "            lines.append('Passable moves: {}'.format(', '.join(nb_strs)))\n"
    "        else:\n"
    "            lines.append('Passable moves: none (surrounded or unexplored)')\n"
    "        if unexplored:\n"
    "            lines.append('Unexplored neighbors: {}'.format(\n"
    "                ', '.join('{}->({},{})'.format(n, nx, ny) for n, nx, ny in unexplored)))\n"
    "        exits = self._room_exits(px, py)\n"
    "        if exits:\n"
    "            if exits['corridors']:\n"
    "                lines.append('Room exits - corridors: {}'.format(exits['corridors']))\n"
    "            if exits['doors']:\n"
    "                lines.append('Room exits - doors (move into to open): {}'.format(exits['doors']))\n"
    "            if exits['unexplored_gaps']:\n"
    "                lines.append('Room exits - unexplored gaps (go here!): {}'.format(exits['unexplored_gaps']))\n"
    "            if not any(exits.values()):\n"
    "                lines.append('Room exits: none found - try search near walls')\n"
    "        legend = self._symbol_legend(obs)\n"
    "        if legend:\n"
    "            lines.append('')\n"
    "            lines.append(legend)\n"
    "        return 'Features:\\n  ' + '\\n  '.join(lines)\n"
    "\n"
    "    # Render\n"
    "\n"
    "    def render(self, obs=None):\n"
    "        if obs is None:\n"
    "            obs = self._obs\n"
    "        b = obs['blstats']\n"
    "        self._update_map_cache(obs)\n"
    "        msg = bytes(obs['message']).decode('utf-8', errors='ignore').strip('\\x00').strip()\n"
    "        inv_lines = []\n"
    "        for i in range(55):\n"
    "            item = bytes(obs['inv_strs'][i]).decode('utf-8', errors='ignore').strip('\\x00').strip()\n"
    "            if item:\n"
    "                letter = chr(obs['inv_letters'][i]) if obs['inv_letters'][i] > 0 else '?'\n"
    "                inv_lines.append('{}) {}'.format(letter, item))\n"
    "        inv_str = ('Inventory ({}): '.format(len(inv_lines)) + '  '.join(inv_lines)) if inv_lines else 'Inventory: empty'\n"
    "        hunger_label = _HUNGER_LABEL.get(int(b[21]), str(b[21]))\n"
    "        stats = ('Turn {} | Dlvl:{} | HP:{}/{} | AC:{} | XP:{} | Gold:{} | '\n"
    "                 'Hunger:{} | Str:{} Dex:{} Con:{}').format(\n"
    "            self.turn, int(b[12]), int(b[10]), int(b[11]), int(b[16]),\n"
    "            int(b[19]), int(b[13]), hunger_label, int(b[3]), int(b[4]), int(b[5]))\n"
    "        parts = [stats]\n"
    "        if msg:\n"
    "            parts.append('Message: {}'.format(msg))\n"
    "        parts.append(self._map_features(obs))\n"
    "        parts.append('Map (@ = you, # = corridor, + = door, > = stairs down, < = stairs up):\\n' + self._render_map_cache(obs))\n"
    "        parts.append(inv_str)\n"
    "        return '\\n'.join(parts)\n"
    "\n"
    "    def render_live(self, last_action=None):\n"
    "        obs = self._obs\n"
    "        if obs is None:\n"
    "            return ''\n"
    "        b = obs['blstats']\n"
    "        msg = bytes(obs['message']).decode('utf-8', errors='ignore').strip('\\x00').strip()\n"
    "        hunger_label = _HUNGER_LABEL.get(int(b[21]), str(b[21]))\n"
    "        stats = 'Turn {} | Dlvl:{} | HP:{}/{} | AC:{} | XP:{} | Gold:{} | Hunger:{}'.format(\n"
    "            self.turn, int(b[12]), int(b[10]), int(b[11]), int(b[16]), int(b[19]), int(b[13]), hunger_label)\n"
    "        if last_action:\n"
    "            stats += ' | >>> {}'.format(last_action)\n"
    "        lines = ['{} NetHack AI {}'.format('-'*20, '-'*20), stats]\n"
    "        if msg:\n"
    "            lines.append('Msg: {}'.format(msg))\n"
    "        lines.append('')\n"
    "        lines.append(self._render_map_cache(obs))\n"
    "        lines.append('')\n"
    "        inv_lines = []\n"
    "        for i in range(55):\n"
    "            item = bytes(obs['inv_strs'][i]).decode('utf-8', errors='ignore').strip('\\x00').strip()\n"
    "            if item:\n"
    "                letter = chr(obs['inv_letters'][i]) if obs['inv_letters'][i] > 0 else '?'\n"
    "                inv_lines.append('{}) {}'.format(letter, item))\n"
    "        if inv_lines:\n"
    "            lines.append('Inventory: ' + '  '.join(inv_lines[:8]))\n"
    "        return '\\n'.join(lines)\n"
    "\n"
    "    def render_debug(self, obs=None):\n"
    "        if obs is None:\n"
    "            obs = self._obs\n"
    "        self._update_map_cache(obs)\n"
    "        return self._render_map_cache(obs)\n"
    "\n"
    "    def _save_log(self, final_reward):\n"
    "        os.makedirs(self.log_dir, exist_ok=True)\n"
    "        ts = datetime.now().strftime('%Y%m%d_%H%M%S')\n"
    "        path = os.path.join(self.log_dir, 'game_{}.json'.format(ts))\n"
    "        with open(path, 'w', encoding='utf-8') as f:\n"
    "            json.dump({'turns': self.turn, 'reward': final_reward, 'history': self.history}, f)\n"
    "\n"
    "    def close(self):\n"
    "        self.env.close()\n"
    "\n"
    "\n"
    "def create_env(character=None, log_dir=None):\n"
    "    return NLEEnv(character=character, log_dir=log_dir)\n"
)

with open(PATH, 'a', encoding='utf-8') as f:
    f.write(APPEND)

lines = open(PATH, encoding='utf-8').readlines()
print('Done. Total lines:', len(lines))
